### ISSUE TITLE
Hosting Static Sites on Amazon S3 - Missing Video

### ISSUE THREAD

**Issue by comjosh64** [mpmenne/launchcode-tv#12]
Was this taken down intentionally, or does the the embedded url just need to be updated?

**Comment by terribleplan** [comment]
Please note that we are actually now using github pages to host this, it is even simpler to do.

**Comment by mpmenne** [comment]
It showed my amazon username so I edited that section out.....   

I think I posted the new one but I could check

**Comment by mpmenne** [comment]
Way more awesomeness
