### ISSUE TITLE
Github pages not updating

### ISSUE THREAD

**Issue by terribleplan** [mpmenne/launchcode-tv#15]
This issue is open to track this stuff. Not sure what the issue is, but I will contact github and try to see what is up with this.

**Comment by terribleplan** [comment]
Sent this:

> There is strange caching going on in MoMenne/launchcode-tv, (I am a collaborator) it's been hours and is not live. http://tv.launchcode.us/

**Comment by terribleplan** [comment]
Github response:

> Hi there,
> 
> There are several page build errors in the page build logs for your GitHub Pages site. This is the latest:
> 
> > A file was included in `lib/isotope/bower_components/isotope/_posts/docs/2010-12-01-introduction.md` that is a symlink or does not exist in your `_includes` directory.
> > 
> > Liquid Exception: The included file '_includes/developer-buy-button.html' should exist and should not be a symlink in lib/isotope/bower_components/isotope/_posts/docs/2010-12-01-introduction.md
> 
> I hope that helps you fix the issue. I recommend that you run your site locally using these instructions, in order to pick up page build errors before pushing to GitHub:
> 
> https://help.github.com/articles/using-jekyll-with-pages
> 
> Thanks,
> James

**Comment by terribleplan** [comment]
My response:

> Hmm, that's odd because we are not using (or at least not trying to use) jekyll. Could it be auto-detecting that because of something in the lib/isotope folder?
> 
> Also, is there any way to get some sort of notification when there is such an issue, this is meant to just server HTML, but if it tries to do some build and fails it would be nice to know about it.
> 
> Best wishes,
> Kegan

**Comment by comjosh64** [comment]
I recieved an email that partially described this error.  It wasn't
something that I understood so I didn't do anything with it.  Am I the only
one that recieved the notification?  I couldn't find any examples of this
error that had a suggestion for a solution.  I did find a mention to the
issue with symlinks, there is a security protocol that restricts symlinks.
There is dissagreement that it is actually making anything more secure.  I
found a suggested solution that involved using "unsafe mode", basically
just disablimg the security.  That doesn't sound like a great option.
Does this site use twitter bootstrap?

**Comment by terribleplan** [comment]
It gets sent to whoever broke the build, I am fixing the issue right now. Github response below...

> Hi Kegan,
> 
> > Also, is there any way to get some sort of notification when there is such an issue
> 
> We email notifications of these page build errors to the GitHub user who pushed the change causing the build failure.
> 
> > this is meant to just server HTML
> 
> You can turn Jekyll off by adding an empty .nojekyll file to the gh-pages branch of your repository. This is documented here:
> 
> https://help.github.com/articles/using-jekyll-with-pages#turning-jekyll-off
> 
> Hope that helps.
> 
> Cheers,
> James

**Comment by comjosh64** [comment]
Great.  I'm sorry guys.  I checked the code really close to make sure it
matched syntax before I merged anything.  Where was the problem?

**Comment by terribleplan** [comment]
It was mike, when he added the isotope. something about paths prefixed with an underscore. Not your fault at all.

**Comment by comjosh64** [comment]
Thank you for finding the problem.  I'm glad it's getting fixed, but I'm
much happier that it wasn't my fault!  I probably should adopt a different
attitude toward team projects... but I still glad it wasn't my fault.

**Comment by terribleplan** [comment]
Dude, it's cool. You never want to be the one to break the build... Mike.

**Comment by mpmenne** [comment]
Nice!   Kegan thanks for finding this man.

**Comment by mpmenne** [comment]
Ha ha lol.    Sh*t happens. :-)

**Comment by comjosh64** [comment]
Oh hey Mike, I'm having readability issues with a couple videos.  Depending
on lighting in the auditorium the text on the screen gets difficult to
read.  I will try a higher resolution on Wednesday,  but I think it may be
that the low light sensitivity just doesn't cut it.  I couldn't even read
the link for the PHPStorm discount.   I think I will embed links to your
screen casts in the videos.  Are all of the screen casts done outside of
the lectures?  I just wonder if the timing will match for any of them.
