### ISSUE TITLE
Isotope?

### ISSUE THREAD

**Issue by terribleplan** [mpmenne/launchcode-tv#5]
How do we feel about using [isotope](http://isotope.metafizzy.co/) to make the columns of videos better?

**Comment by mpmenne** [comment]
I haven't seen that before.  That looks awesome!

**Comment by terribleplan** [comment]
Well, I'll mess around with it in a bit then.

**Comment by mpmenne** [comment]
Right on.  I'm going to get a dev license tonight and play around with it
as well... that looks really cool

**Comment by terribleplan** [comment]
It's free for open source, but yeah we bought it for Pushup.

**Comment by terribleplan** [comment]
The typical way you would do it in isotope is to load them all into a div and let isotope do the filtering, I have no clue how to do that "The Angular Way". Thoughts?

**Comment by mpmenne** [comment]
I found an isotope-angular directive that looks like it could work pretty
well.  I'm going to give it a shot

**Comment by mpmenne** [comment]
https://github.com/mankindsoftware/angular-isotope

**Comment by terribleplan** [comment]
Cool, i'm working on #6. Once you get the angular stuff figured out there are some minor changes that I want to make concerning the gallery view and responsiveness.

**Comment by mpmenne** [comment]
That will look really good with isotope.  

I'm just figuring out the filtering.   Should have it done by tonight

**Comment by terribleplan** [comment]
Are you anywhere near? If not we can just implement a variation of what I did with the calendar, which will be better at least

**Comment by comjosh64** [comment]
I'm on my way.  Will be there in a few.  I am bringing a full DSLR with
some video capability.  The sensor overheats after about 15 min so I will
have to use it to augment the cell phone vid.  -Josh

**Comment by terribleplan** [comment]
Fixed at 861ef2d21507bcb41e3f2759028c7bc7de41f5b1
